[package]
authors = ["Simon Walker <s.r.walker101@googlemail.com>"]
name = "sdl2testing"
version = "0.1.0"

[dependencies]
time = "0.1.38"

[dependencies.sdl2]
version = "0.30.0"
default-features = false
features = ["ttf", "image", "mixer"]
